import PageAnimatePresence from "@/components/PageAnimatePresence";
import "./globals.css";
// import { MainParticles } from "@/components/MainParticles";
import { CookiesProvider } from "next-client-cookies/server";

export const metadata = {
  title: "MFS GAME",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        {/* <MainParticles /> */}
        <PageAnimatePresence>
          <CookiesProvider>{children}</CookiesProvider>
        </PageAnimatePresence>
      </body>
    </html>
  );
}
